name: Build Solstice
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Patch CMake configuration
        shell: bash
        run: |
          sed -i '/UNITY_BUILD/d' CMakeLists.txt
          sed -i '/[kK]iero/d' CMakeLists.txt
      - name: Build Project
        run: |
          cmake -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_UNITY_BUILD=OFF
          cmake --build build --config Release
      - name: Upload DLL Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-cheat
          path: build/Release/*.dll
